#!/bin/bash
MAC=$(cat /config/bluetooth.config | grep -i 'mac-address' | cut -d= -f2)
echo "pcm.bt-device { 
        type plug 
        slave.pcm { 
                type bluealsa 
                device "$MAC" 
                profile "a2dp" 
                delay 1000 
        } 
}" > ~/.asoundsrc  
bluetoothctl power on
echo "scanning devices for 5 seconds.."
bluetoothctl scan on &
SCANPID=$!
sleep 5
kill -INT $SCANPID 
yes | bluetoothctl pair $MAC
bluetoothctl trust $MAC
bluetoothctl connect $MAC
echo "connection done.. If the device isn't available set the device in pairing mode and re-create the container"
touch /config/setupdone